### ISSUE TITLE
pixel2coord in get_image_download.py

### ISSUE THREAD

**Issue by mistborn17** [nealjean/predicting-poverty#6]
Hi Neal,

My name is Kishen. I was looking at your code.

In pixel2coord in /scripts/get_image_download.py function.
Every pixel spans some latitude and longitude.
Shouldn't you use mean of the pixel's latitude and longitude.
That will correspond to 0.45km shift on the ground?

**Comment by sangmichaelxie** [comment]
Hi Kishen, 
Thanks for the comment. I believe you're correct in that it could correspond to a shift on the ground. This current method selects the upper left corner of the box. In this case we are trying to get the images from a 10km x 10km box around the original coordinate; we use the original coordinates to find the bounding box of tiled pixels and transform the pixels back to coordinate locations. However, we're finding the top left corner of each pixel instead of the center, which could cause an overall shift. With regards to the results that come out of the code, 0.45km shouldn't be a consequential shift especially because of the inherent noise (2-5 km shift in any direction) in the original location. We've done many tests on the robustness of the results to varying noise and quality of the selection of input images, and they all do pretty well.

**Comment by mistborn17** [comment]
Hey, won't this method affect your night light deep cnn training?

**Comment by sangmichaelxie** [comment]
It should not, since the transfer learning step is done by first picking the coordinate locations for the input around DHS survey locations and then finding the corresponding nighttime light value, not using the inverse mapping.

**Comment by mistborn17** [comment]
Yeah ,true.
